title: Tukain's Blog
lang: pt-br
author: Tukain
description: O blog de um nerd de computador
url: https://tukain.xyz
timezone: America/Recife
encoding: utf-8

#plugins:
#  - jekyll-last-modified-at
#  - jekyll-sitemap
#  - jekyll-seo-tag
#  - jekyll-toc
#  - jekyll-target-blank
#  - jekyll-feed
#  - liquid_reading_time
#
#jekyll-admin:
#  homepage: "posts"
#
#last-modified-at:
#  date-format: '%d-%b-%y'

collections:
  posts:
    output: true
    permalink: /blog/posts/:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      author: Tukain
      toc: true
  - scope:
      path: "blog.md"
    values:
      permalink: "/blog/index.html"

