title: Tukain's Blog
lang: pt-br
author: Tukain
description: O blog de um nerd de computador
url: https://tukain.xyz
timezone: America/Recife
encoding: utf-8

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap

last-modified-at:
  date-format: '%d-%b-%y'

paginate: false

collections:
  posts:
    output: true
    permalink: /blog/posts/:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: base
  - scope:
      type: posts
    values:
      layout: post
      author: Tukain
  - scope:
      path: "blog.md"
    values:
      permalink: "/blog/index.html"

